### Create a new thread with media (Private Route)
POST http://localhost:4000/api/threads/create
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MDU2NjM0MCwiZXhwIjoxNzYwNTY3MjQwfQ.t-7ZBRjQ2vpZrGmyhEQXJm1DyOtW2T9ceRSTdyNVrmc
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"

To jest treść mojego nowego, ekscytującego wątku z obrazkiem!
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="media"; filename="background.jpg"
Content-Type: image/jpeg

< /Users/michas/Downloads/background.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="media"; filename="avatar.png"
Content-Type: image/png

< /Users/michas/Downloads/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Create a new thread without media (Private Route)
POST http://localhost:4000/api/threads/create
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MDg3Mjc3NSwiZXhwIjoxNzYwODczNjc1fQ.L-ibApGGq3YA09df87J29tpRMv6PlgCvrbUfnicpgno
Content-Type: application/json

{
  "content": "To jest prosty wątek tekstowy, bez żadnych mediów."
}


### Delete a thread (Private Route)
DELETE http://localhost:4000/api/threads/1951082c-e0bc-4be8-87b9-1a1ba3bf3014
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MDU2Mjk3NCwiZXhwIjoxNzYwNTYzODc0fQ.veo5eWTYQhSoeN08z8XhK3wtZOybfq7GaRzX3gUgenU


### Update an existing thread (Private Route)
PATCH http://localhost:4000/api/threads/656fe7cf-8096-4c03-b7b7-b724ebd35a61
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MDg3Mjc3NSwiZXhwIjoxNzYwODczNjc1fQ.L-ibApGGq3YA09df87J29tpRMv6PlgCvrbUfnicpgno
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"

To jest zaktualizowana, nowa treść mojego wątku.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="existingMediaUrls"

["https://res.cloudinary.com/dfvtjkt7y/image/upload/v1760566442/mindweave_profiles/fhw63qpg9im4jjmwwub4.png"]
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="media"; filename="nowy-obrazek.png"
Content-Type: image/png

< /Users/michas/Downloads/filmfest.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get all public threads (first page, default limit)
GET http://localhost:4000/api/threads/

### Get all public threads with pagination (page 2, 5 items per page)
GET http://localhost:4000/api/threads?page=2&limit=5

### Get all public threads with a search term
GET http://localhost:4000/api/threads?search=test

### Get all public threads with search and pagination
GET http://localhost:4000/api/threads?search=zaktualizowana&page=1&limit=3

### Get a single thread by its ID (Public Route)
GET http://localhost:4000/api/threads/ab809b06-de0e-4c7e-b95e-5af9e57c891c

### Toggle like on a thread (Private Route)
POST http://localhost:4000/api/threads/ab809b06-de0e-4c7e-b95e-5af9e57c891c/like
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTE2NTQwNSwiZXhwIjoxNzYxMTY2MzA1fQ.sMueVGZMmHpSM0CfPTbpKsS3D3hYqHZjKDQKX_YYseo

### Get all likes for a specific thread (Private Route)
GET http://localhost:4000/api/threads/ab809b06-de0e-4c7e-b95e-5af9e57c891c/likes
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTE2NTQwNSwiZXhwIjoxNzYxMTY2MzA1fQ.sMueVGZMmHpSM0CfPTbpKsS3D3hYqHZjKDQKX_YYseo

### Get all comments for a thread (Private Route)
GET http://localhost:4000/api/threads/ab809b06-de0e-4c7e-b95e-5af9e57c891c/comments
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MDk5NDE5MiwiZXhwIjoxNzYwOTk1MDkyfQ.cQFeiOetPji0gHhLtEBOVjDvlknsTjme4AWonsWyDo8

### Add comment to a thread (Private Route)
POST http://localhost:4000/api/threads/ab809b06-de0e-4c7e-b95e-5af9e57c891c/comments
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MDk5NDE5MiwiZXhwIjoxNzYwOTk1MDkyfQ.cQFeiOetPji0gHhLtEBOVjDvlknsTjme4AWonsWyDo8
Content-Type: application/json

{
  "content": "It's amazing comment 2",
  "parentId": "cb6dcac8-2344-40d5-ad25-b5bc9f23d908"
}

### Delete comment from a thread (Private Route)
DELETE http://localhost:4000/api/threads/comments/5de15bc5-e04a-4ce5-8f4d-b9e15e63b9c3
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MDk5NDE5MiwiZXhwIjoxNzYwOTk1MDkyfQ.cQFeiOetPji0gHhLtEBOVjDvlknsTjme4AWonsWyDo8

### Update a comment (Private Route)
PATCH http://localhost:4000/api/threads/comments/5de15bc5-e04a-4ce5-8f4d-b9e15e63b9c3
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MDk5NDE5MiwiZXhwIjoxNzYwOTk1MDkyfQ.cQFeiOetPji0gHhLtEBOVjDvlknsTjme4AWonsWyDo8

{
  "content": "To jest nowa, zaktualizowana treść mojego komentarza."
}


### Get all replies for a specific comment (Private Route)
GET http://localhost:4000/api/threads/comments/cb6dcac8-2344-40d5-ad25-b5bc9f23d908/replies
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MDk5NDE5MiwiZXhwIjoxNzYwOTk1MDkyfQ.cQFeiOetPji0gHhLtEBOVjDvlknsTjme4AWonsWyDo8

### Toggle like on a comment (Private Route)
POST http://localhost:4000/api/threads/comments/533208c5-76e8-4bb0-8a05-7ddffc2c5b20/like
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTA3ODA5OSwiZXhwIjoxNzYxMDc4OTk5fQ.zu75DXFOYrABnYB5neabFJV-eVg0qQ1xMQ1bLx8PqlU

### Get all likes for a specific comment (Private Route)
GET http://localhost:4000/api/threads/comments/533208c5-76e8-4bb0-8a05-7ddffc2c5b20/likes
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTE2NTQwNSwiZXhwIjoxNzYxMTY2MzA1fQ.sMueVGZMmHpSM0CfPTbpKsS3D3hYqHZjKDQKX_YYseo

### Share a thread (Retweet style - no content)
POST http://localhost:4000/api/threads/ab809b06-de0e-4c7e-b95e-5af9e57c891c/share
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTI1NDc5MCwiZXhwIjoxNzYxMjU1NjkwfQ.JZKbIlK18CpQc6R72JzWW3OyJJ1KBIqMJeqhQwMlZk8
Content-Type: application/json

{}

###

### Share a thread with a comment (Quote Tweet style)
POST http://localhost:4000/api/threads/ab809b06-de0e-4c7e-b95e-5af9e57c891c/share
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTI1NDc5MCwiZXhwIjoxNzYxMjU1NjkwfQ.JZKbIlK18CpQc6R72JzWW3OyJJ1KBIqMJeqhQwMlZk8
Content-Type: application/json

{
  "content": "To jest mój komentarz do udostępnianego wątku!"
}