// PUBLIC PATHS
const PUBLIC_DASHBOARD_PATH = '/'
const LOGIN_PATH = '/login'
const SIGN_UP_PATH = '/sign-up'
const FORGOT_PASSWORD_PATH = '/forgot-password'
const ACTIVE_ACCOUNT_PATH = '/active-account'
const RESET_PASSWORD_PATH = '/reset-password'
const ACTIVATE_ACCOUNT_PATH = '/activate'

// PRIVATE PATHS
const DASHBOARD_PATH = '/dashboard'
const SETTINGS_PATH = '/settings'

export { PUBLIC_DASHBOARD_PATH, LOGIN_PATH, ACTIVATE_ACCOUNT_PATH, SIGN_UP_PATH, FORGOT_PASSWORD_PATH, ACTIVE_ACCOUNT_PATH, RESET_PASSWORD_PATH, DASHBOARD_PATH, SETTINGS_PATH }