### Get all categories for a specific user (Public Route)
GET http://localhost:4000/api/publications/user/e7f1a7f7-f845-48a7-b5ed-2757e9d3d96f/categories


### Create a new category (Private Route)
POST http://localhost:4000/api/publications/categories
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTU5Mzg4OSwiZXhwIjoxNzYxNTk0Nzg5fQ.vynnpwUKDCPcOV56OfkL1Vf-MScCJUkna7eKCPOLj28

{
  "name": "Moja Nowa Kategoria 2",
  "description": "Opis nowej, wspaniałej kategorii artykułów.",
  "slug": "moja-nowa-kategoria-2"
}


### Get a single category by ID (Public Route)
GET http://localhost:4000/api/publications/categories/moja-nowa-kategoria-2


### Update a category (Private Route)
PATCH http://localhost:4000/api/publications/categories/88e64080-6f19-4ba2-b221-371787381033
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTU5Mzg4OSwiZXhwIjoxNzYxNTk0Nzg5fQ.vynnpwUKDCPcOV56OfkL1Vf-MScCJUkna7eKCPOLj28

{
  "name": "Zaktualizowana Nazwa Kategorii",
  "slug": "zaktualizowany-slug"
}


### Delete a category (Private Route)
DELETE http://localhost:4000/api/publications/categories/a400894f-0ddc-4547-9e1e-fc1abba2be28
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTU5Mzg4OSwiZXhwIjoxNzYxNTk0Nzg5fQ.vynnpwUKDCPcOV56OfkL1Vf-MScCJUkna7eKCPOLj28


### Create a new article with a cover image (Private Route)
POST http://localhost:4000/api/publications/articles/create
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryArtikel
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTY4NzI1MSwiZXhwIjoxNzYxNjg4MTUxfQ.CrpomEHHrsM4DU2MCbqUacbIPec5PfDiUQuTYavVm7s

------WebKitFormBoundaryArtikel
Content-Disposition: form-data; name="title"

Mój Niesamowity Tytuł Artykułu
------WebKitFormBoundaryArtikel
Content-Disposition: form-data; name="contentHtml"

<p>To jest <strong>bardzo</strong> ważna treść mojego artykułu w formacie HTML.</p>
------WebKitFormBoundaryArtikel
Content-Disposition: form-data; name="categoryId"

88e64080-6f19-4ba2-b221-371787381033
------WebKitFormBoundaryArtikel
Content-Disposition: form-data; name="slug"

moj-niesamowity-artykul-slug
------WebKitFormBoundaryArtikel
Content-Disposition: form-data; name="coverArticleImage"; filename="cover.jpg"
Content-Type: image/jpeg

< /Users/michas/Downloads/avatar.png
------WebKitFormBoundaryArtikel--


### Create a new article without a cover image (Private Route)
POST http://localhost:4000/api/publications/articles/create
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTc3MDYwMiwiZXhwIjoxNzYxNzcxNTAyfQ.iEmKVw8FPoh2d_S3bqnkLdI70a9447s13pZP-6nJ348

{
  "title": "Artykuł bez obrazka",
  "contentHtml": "<p>Treść artykułu bez obrazka okładkowego.</p>",
  "categoryId": "88e64080-6f19-4ba2-b221-371787381033",
  "slug": "artykul-bez-obrazka-2"
}

### Change an article's status (Private Route)
PATCH http://localhost:4000/api/publications/articles/c4ab9074-e839-4687-a07f-910fc487d054/status
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MjE5NTM1OSwiZXhwIjoxNzYyMTk2MjU5fQ.A6k0cZQHF-P3hXF6lzSTiznkPWdQ9oYqTCIrPiT74Hk

{
  "status": "PUBLISHED"
}


### Change an article's status back to draft
PATCH http://localhost:4000/api/publications/articles/c60e4503-a47e-4faa-a7f6-be204752d1b2/status
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTk5MTg3NSwiZXhwIjoxNzYxOTkyNzc1fQ.UsbSNsFScpl2AfJgHzjnumj3fzn_PfM8r2-suZ99bq0

{
  "status": "DRAFT"
}

### Delete an article (Private Route)
DELETE http://localhost:4000/api/publications/articles/ae29588e-7973-40bd-ac6f-8c15589cfd2d
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTc3MDYwMiwiZXhwIjoxNzYxNzcxNTAyfQ.iEmKVw8FPoh2d_S3bqnkLdI70a9447s13pZP-6nJ348


### Update an article (Text + New Cover Image) (Private Route)
PATCH http://localhost:4000/api/publications/articles/c60e4503-a47e-4faa-a7f6-be204752d1b2
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryUpdateArticle
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTc3Mjg3MiwiZXhwIjoxNzYxNzczNzcyfQ.vpRgI5A2MSZ88yKak01sNFycXjZIY24VCky9isErA9k

------WebKitFormBoundaryUpdateArticle
Content-Disposition: form-data; name="title"

To jest mój zaktualizowany tytuł!
------WebKitFormBoundaryUpdateArticle
Content-Disposition: form-data; name="contentHtml"

<p>Zaktualizowana <b>treść</b> HTML.</p>
------WebKitFormBoundaryUpdateArticle
Content-Disposition: form-data; name="categoryId"

88e64080-6f19-4ba2-b221-371787381033
------WebKitFormBoundaryUpdateArticle
Content-Disposition: form-data; name="slug"

zaktualizowany-super-slug
------WebKitFormBoundaryUpdateArticle
Content-Disposition: form-data; name="coverArticleImage"; filename="new-cover.jpg"
Content-Type: image/jpeg

< /Users/michas/Downloads/background.jpg
------WebKitFormBoundaryUpdateArticle--


### Update an article (Text + Remove Cover Image) (Private Route)
PATCH http://localhost:4000/api/publications/articles/c60e4503-a47e-4faa-a7f6-be204752d1b2
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryRemoveImage
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTc3Mjg3MiwiZXhwIjoxNzYxNzczNzcyfQ.vpRgI5A2MSZ88yKak01sNFycXjZIY24VCky9isErA9k

------WebKitFormBoundaryRemoveImage
Content-Disposition: form-data; name="title"

Tylko zmieniam tytuł i usuwam obrazek
------WebKitFormBoundaryRemoveImage
Content-Disposition: form-data; name="coverImage"

null
------WebKitFormBoundaryRemoveImage--

###

### Update an article (Text Only, No Image Change) (Private Route)
PATCH http://localhost:4000/api/publications/articles/c60e4503-a47e-4faa-a7f6-be204752d1b2
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryTextOnly
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTc3Mjg3MiwiZXhwIjoxNzYxNzczNzcyfQ.vpRgI5A2MSZ88yKak01sNFycXjZIY24VCky9isErA9k

------WebKitFormBoundaryTextOnly
Content-Disposition: form-data; name="title"

Zmieniam tylko tytuł, nic więcej
------WebKitFormBoundaryTextOnly
Content-Disposition: form-data; name="slug"

nowy-slug-bez-zmiany-obrazka
------WebKitFormBoundaryTextOnly--


### Get a single article (Public / Smart Route)
GET http://localhost:4000/api/publications/articles/artykul-bez-obrazka


### Get a single article (Private / As Owner)
GET http://localhost:4000/api/publications/articles/c60e4503-a47e-4faa-a7f6-be204752d1b2
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MTk5MTg3NSwiZXhwIjoxNzYxOTkyNzc1fQ.UsbSNsFScpl2AfJgHzjnumj3fzn_PfM8r2-suZ99bq0

### Get all PUBLISHED articles in a category (Public Route)
GET http://localhost:4000/api/publications/user/e7f1a7f7-f845-48a7-b5ed-2757e9d3d96f/categories/88e64080-6f19-4ba2-b221-371787381033/articles/published


### Get all DRAFT articles (Private Route - requires auth)
GET http://localhost:4000/api/publications/user/e7f1a7f7-f845-48a7-b5ed-2757e9d3d96f/categories/88e64080-6f19-4ba2-b221-371787381033/articles/draft
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MjE5NTM1OSwiZXhwIjoxNzYyMTk2MjU5fQ.A6k0cZQHF-P3hXF6lzSTiznkPWdQ9oYqTCIrPiT74Hk


### Get PUBLISHED articles with pagination and search
GET http://localhost:4000/api/publications/user/e7f1a7f7-f845-48a7-b5ed-2757e9d3d96f/categories/88e64080-6f19-4ba2-b221-371787381033/articles/published?page=1&limit=5&search=obrazka

### Rate an article as "LIKE" (Private Route)
POST http://localhost:4000/api/publications/articles/c4ab9074-e839-4687-a07f-910fc487d054/rate
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MjE5OTIxNSwiZXhwIjoxNzYyMjAwMTE1fQ.umGsZC7VnygOpom2lxTz8DvmmyXr2g_0Jegh1kbXx_c

{
  "rate": "LIKE"
}


### Rate an article as "DISLIKE" (Private Route)
POST http://localhost:4000/api/publications/articles/c4ab9074-e839-4687-a07f-910fc487d054/rate
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlN2YxYTdmNy1mODQ1LTQ4YTctYjVlZC0yNzU3ZTlkM2Q5NmYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc2MjE5OTIxNSwiZXhwIjoxNzYyMjAwMTE1fQ.umGsZC7VnygOpom2lxTz8DvmmyXr2g_0Jegh1kbXx_c

{
  "rate": "DISLIKE"
}