### Register User
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "email": "cleveland.nolan@ethereal.email",
  "password": "Password123!",
  "name": "Maciek",
  "surname": "Bobo",
  "sex": "f",
  "birthday": "2024-04-24T00:00:00.000Z"
}

### Activate user account with the received code
POST http://localhost:4000/api/auth/activate
Content-Type: application/json

{
  "token": "91E0Y"
}

### Request Password Reset
POST http://localhost:4000/api/auth/request-password-reset
Content-Type: application/json

{
  "email": "cleveland.nolan@ethereal.email"
}

### Reset Password
POST http://localhost:4000/api/auth/reset-password
Content-Type: application/json

{
  "token": "WJG2LXJY3VUVU4BZCKU5O1I3",
  "newPassword": "NewSecurePassword123!"
}

### Login User
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}

### Refresh Access Token
POST http://localhost:4000/api/auth/refresh
Content-Type: application/json

### Update User Profile with Images
PATCH http://localhost:4000/api/auth/profile/update
Content-Type: multipart/form-data; boundary=my-app-boundary
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZTIxYzQzZi0zNjkzLTQ5YTYtYWFjYS1iZDUwZDFkZjg3NDYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc1MzczNzU1NSwiZXhwIjoxNzUzNzM4NDU1fQ.6yUbgvyckiDf0xktPDfErbCn2ZELmmwK9bu4LxArQqs

--my-app-boundary
Content-Disposition: form-data; name="name"

Pawełek
--my-app-boundary
Content-Disposition: form-data; name="surname"

Luzny
--my-app-boundary
Content-Disposition: form-data; name="birthday"

2024-04-24T00:00:00.000Z
--my-app-boundary
Content-Disposition: form-data; name="sex"

Male
--my-app-boundary
Content-Disposition: form-data; name="slug"

bobo-lobo
--my-app-boundary
Content-Disposition: form-data; name="profileImage"; filename="my_avatar.jpg"
Content-Type: image/jpeg

< /Users/michas/Downloads/avatar.png
--my-app-boundary
Content-Disposition: form-data; name="coverImage"; filename="my_cover.png"
Content-Type: image/png

< /Users/michas/Downloads/background.jpg
--my-app-boundary--

### Get User Profile (Protected Route)
GET http://localhost:4000/api/auth/profile
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZTIxYzQzZi0zNjkzLTQ5YTYtYWFjYS1iZDUwZDFkZjg3NDYiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTc1MzczNzU1NSwiZXhwIjoxNzUzNzM4NDU1fQ.6yUbgvyckiDf0xktPDfErbCn2ZELmmwK9bu4LxArQqs
###

### Logout and Revoke Refresh Token
POST http://localhost:4000/api/auth/logout