### Register User
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "Password123!",
  "name": "Maciek",
  "surname": "Bobo",
  "sex": "f",
  "birthday": "2024-04-24T00:00:00.000Z"
}

### Update User Profile
PUT http://localhost:4000/api/auth/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDYyNTg0OSwiZXhwIjoxNzUwNjI5NDQ5fQ.xFZBBSDkmyYGSadHDhqy0Mk1GZFVEagVznLp3kSJXns

{
  "name": "Pawełek",
  "surname": "Luzny",
  "birthday": "1995-07-15T00:00:00.000Z",
  "sex": "m"
}

### Login User
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!"
}

### Get User Profile (Protected Route)
GET http://localhost:4000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDYyNDg2NywiZXhwIjoxNzUwNjI4NDY3fQ.06degAlw4DHyMBxKozV1CLxe8pni4n54bANbly56GLQ

###